// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfirmationReceipt.proto

package com.datmedia.mediaplayer.messages.Enrollment;

public final class ConfirmationReceiptOuterClass {
  private ConfirmationReceiptOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConfirmationReceiptOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.datmedia.mediaplayer.androidrequestresponse.ConfirmationReceipt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes ChallengeResponse = 1;</code>
     */
    boolean hasChallengeResponse();
    /**
     * <code>required bytes ChallengeResponse = 1;</code>
     */
    com.google.protobuf.ByteString getChallengeResponse();
  }
  /**
   * Protobuf type {@code com.datmedia.mediaplayer.androidrequestresponse.ConfirmationReceipt}
   */
  public static final class ConfirmationReceipt extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.datmedia.mediaplayer.androidrequestresponse.ConfirmationReceipt)
      ConfirmationReceiptOrBuilder {
    // Use ConfirmationReceipt.newBuilder() to construct.
    private ConfirmationReceipt(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ConfirmationReceipt(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ConfirmationReceipt defaultInstance;
    public static ConfirmationReceipt getDefaultInstance() {
      return defaultInstance;
    }

    public ConfirmationReceipt getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ConfirmationReceipt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              challengeResponse_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ConfirmationReceiptOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_ConfirmationReceipt_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ConfirmationReceiptOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_ConfirmationReceipt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ConfirmationReceipt.class, Builder.class);
    }

    public static com.google.protobuf.Parser<ConfirmationReceipt> PARSER =
        new com.google.protobuf.AbstractParser<ConfirmationReceipt>() {
      public ConfirmationReceipt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfirmationReceipt(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<ConfirmationReceipt> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CHALLENGERESPONSE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString challengeResponse_;
    /**
     * <code>required bytes ChallengeResponse = 1;</code>
     */
    public boolean hasChallengeResponse() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes ChallengeResponse = 1;</code>
     */
    public com.google.protobuf.ByteString getChallengeResponse() {
      return challengeResponse_;
    }

    private void initFields() {
      challengeResponse_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasChallengeResponse()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, challengeResponse_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, challengeResponse_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ConfirmationReceipt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ConfirmationReceipt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ConfirmationReceipt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ConfirmationReceipt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ConfirmationReceipt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ConfirmationReceipt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ConfirmationReceipt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ConfirmationReceipt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ConfirmationReceipt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ConfirmationReceipt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ConfirmationReceipt prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.datmedia.mediaplayer.androidrequestresponse.ConfirmationReceipt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.datmedia.mediaplayer.androidrequestresponse.ConfirmationReceipt)
        ConfirmationReceiptOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ConfirmationReceiptOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_ConfirmationReceipt_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ConfirmationReceiptOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_ConfirmationReceipt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ConfirmationReceipt.class, Builder.class);
      }

      // Construct using com.datmedia.mediaplayer.androidrequestresponse.ConfirmationReceiptOuterClass.ConfirmationReceipt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        challengeResponse_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ConfirmationReceiptOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_ConfirmationReceipt_descriptor;
      }

      public ConfirmationReceipt getDefaultInstanceForType() {
        return ConfirmationReceipt.getDefaultInstance();
      }

      public ConfirmationReceipt build() {
        ConfirmationReceipt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ConfirmationReceipt buildPartial() {
        ConfirmationReceipt result = new ConfirmationReceipt(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.challengeResponse_ = challengeResponse_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ConfirmationReceipt) {
          return mergeFrom((ConfirmationReceipt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ConfirmationReceipt other) {
        if (other == ConfirmationReceipt.getDefaultInstance()) return this;
        if (other.hasChallengeResponse()) {
          setChallengeResponse(other.getChallengeResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasChallengeResponse()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ConfirmationReceipt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ConfirmationReceipt) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString challengeResponse_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes ChallengeResponse = 1;</code>
       */
      public boolean hasChallengeResponse() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes ChallengeResponse = 1;</code>
       */
      public com.google.protobuf.ByteString getChallengeResponse() {
        return challengeResponse_;
      }
      /**
       * <code>required bytes ChallengeResponse = 1;</code>
       */
      public Builder setChallengeResponse(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        challengeResponse_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes ChallengeResponse = 1;</code>
       */
      public Builder clearChallengeResponse() {
        bitField0_ = (bitField0_ & ~0x00000001);
        challengeResponse_ = getDefaultInstance().getChallengeResponse();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.datmedia.mediaplayer.androidrequestresponse.ConfirmationReceipt)
    }

    static {
      defaultInstance = new ConfirmationReceipt(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.datmedia.mediaplayer.androidrequestresponse.ConfirmationReceipt)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datmedia_mediaplayer_androidrequestresponse_ConfirmationReceipt_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_datmedia_mediaplayer_androidrequestresponse_ConfirmationReceipt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031ConfirmationReceipt.proto\022/com.datmedi" +
      "a.mediaplayer.androidrequestresponse\"0\n\023" +
      "ConfirmationReceipt\022\031\n\021ChallengeResponse" +
      "\030\001 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_datmedia_mediaplayer_androidrequestresponse_ConfirmationReceipt_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_datmedia_mediaplayer_androidrequestresponse_ConfirmationReceipt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_datmedia_mediaplayer_androidrequestresponse_ConfirmationReceipt_descriptor,
        new String[] { "ChallengeResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
