// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnrollmentConfirmation.proto

package com.datmedia.mediaplayer.messages.Enrollment;

public final class EnrollmentConfirmationOuterClass {
  private EnrollmentConfirmationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EnrollmentConfirmationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 DeviceId = 1;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>required int32 DeviceId = 1;</code>
     */
    int getDeviceId();

    /**
     * <code>required string EncryptedChallenge = 2;</code>
     */
    boolean hasEncryptedChallenge();
    /**
     * <code>required string EncryptedChallenge = 2;</code>
     */
    java.lang.String getEncryptedChallenge();
    /**
     * <code>required string EncryptedChallenge = 2;</code>
     */
    com.google.protobuf.ByteString
        getEncryptedChallengeBytes();
  }
  /**
   * Protobuf type {@code com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmation}
   */
  public static final class EnrollmentConfirmation extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmation)
      EnrollmentConfirmationOrBuilder {
    // Use EnrollmentConfirmation.newBuilder() to construct.
    private EnrollmentConfirmation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EnrollmentConfirmation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EnrollmentConfirmation defaultInstance;
    public static EnrollmentConfirmation getDefaultInstance() {
      return defaultInstance;
    }

    public EnrollmentConfirmation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EnrollmentConfirmation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              deviceId_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              encryptedChallenge_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.internal_static_com_datmedia_mediaplayer_messages_Enrollment_EnrollmentConfirmation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.internal_static_com_datmedia_mediaplayer_messages_Enrollment_EnrollmentConfirmation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation.class, com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation.Builder.class);
    }

    public static com.google.protobuf.Parser<EnrollmentConfirmation> PARSER =
        new com.google.protobuf.AbstractParser<EnrollmentConfirmation>() {
      public EnrollmentConfirmation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnrollmentConfirmation(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EnrollmentConfirmation> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DEVICEID_FIELD_NUMBER = 1;
    private int deviceId_;
    /**
     * <code>required int32 DeviceId = 1;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 DeviceId = 1;</code>
     */
    public int getDeviceId() {
      return deviceId_;
    }

    public static final int ENCRYPTEDCHALLENGE_FIELD_NUMBER = 2;
    private java.lang.Object encryptedChallenge_;
    /**
     * <code>required string EncryptedChallenge = 2;</code>
     */
    public boolean hasEncryptedChallenge() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string EncryptedChallenge = 2;</code>
     */
    public java.lang.String getEncryptedChallenge() {
      java.lang.Object ref = encryptedChallenge_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          encryptedChallenge_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string EncryptedChallenge = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEncryptedChallengeBytes() {
      java.lang.Object ref = encryptedChallenge_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        encryptedChallenge_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      deviceId_ = 0;
      encryptedChallenge_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEncryptedChallenge()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, deviceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEncryptedChallengeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, deviceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEncryptedChallengeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmation)
        com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.internal_static_com_datmedia_mediaplayer_messages_Enrollment_EnrollmentConfirmation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.internal_static_com_datmedia_mediaplayer_messages_Enrollment_EnrollmentConfirmation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation.class, com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation.Builder.class);
      }

      // Construct using com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deviceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        encryptedChallenge_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.internal_static_com_datmedia_mediaplayer_messages_Enrollment_EnrollmentConfirmation_descriptor;
      }

      public com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation getDefaultInstanceForType() {
        return com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation.getDefaultInstance();
      }

      public com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation build() {
        com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation buildPartial() {
        com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation result = new com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.encryptedChallenge_ = encryptedChallenge_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation) {
          return mergeFrom((com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation other) {
        if (other == com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          setDeviceId(other.getDeviceId());
        }
        if (other.hasEncryptedChallenge()) {
          bitField0_ |= 0x00000002;
          encryptedChallenge_ = other.encryptedChallenge_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDeviceId()) {
          
          return false;
        }
        if (!hasEncryptedChallenge()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmationOuterClass.EnrollmentConfirmation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int deviceId_ ;
      /**
       * <code>required int32 DeviceId = 1;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 DeviceId = 1;</code>
       */
      public int getDeviceId() {
        return deviceId_;
      }
      /**
       * <code>required int32 DeviceId = 1;</code>
       */
      public Builder setDeviceId(int value) {
        bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 DeviceId = 1;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object encryptedChallenge_ = "";
      /**
       * <code>required string EncryptedChallenge = 2;</code>
       */
      public boolean hasEncryptedChallenge() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string EncryptedChallenge = 2;</code>
       */
      public java.lang.String getEncryptedChallenge() {
        java.lang.Object ref = encryptedChallenge_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            encryptedChallenge_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string EncryptedChallenge = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEncryptedChallengeBytes() {
        java.lang.Object ref = encryptedChallenge_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          encryptedChallenge_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string EncryptedChallenge = 2;</code>
       */
      public Builder setEncryptedChallenge(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        encryptedChallenge_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string EncryptedChallenge = 2;</code>
       */
      public Builder clearEncryptedChallenge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        encryptedChallenge_ = getDefaultInstance().getEncryptedChallenge();
        onChanged();
        return this;
      }
      /**
       * <code>required string EncryptedChallenge = 2;</code>
       */
      public Builder setEncryptedChallengeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        encryptedChallenge_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmation)
    }

    static {
      defaultInstance = new EnrollmentConfirmation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.datmedia.mediaplayer.messages.Enrollment.EnrollmentConfirmation)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datmedia_mediaplayer_messages_Enrollment_EnrollmentConfirmation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_datmedia_mediaplayer_messages_Enrollment_EnrollmentConfirmation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034EnrollmentConfirmation.proto\022,com.datm" +
      "edia.mediaplayer.messages.Enrollment\"F\n\026" +
      "EnrollmentConfirmation\022\020\n\010DeviceId\030\001 \002(\005" +
      "\022\032\n\022EncryptedChallenge\030\002 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_datmedia_mediaplayer_messages_Enrollment_EnrollmentConfirmation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_datmedia_mediaplayer_messages_Enrollment_EnrollmentConfirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_datmedia_mediaplayer_messages_Enrollment_EnrollmentConfirmation_descriptor,
        new java.lang.String[] { "DeviceId", "EncryptedChallenge", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
