// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnrollmentConfirmation.proto

package com.datmedia.mediaplayer.messages.Enrollment;

public final class EnrollmentConfirmationOuterClass {
  private EnrollmentConfirmationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EnrollmentConfirmationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.datmedia.mediaplayer.androidrequestresponse.EnrollmentConfirmation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 DeviceId = 1;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>required int32 DeviceId = 1;</code>
     */
    int getDeviceId();

    /**
     * <code>required bytes EncryptedChallenge = 2;</code>
     */
    boolean hasEncryptedChallenge();
    /**
     * <code>required bytes EncryptedChallenge = 2;</code>
     */
    com.google.protobuf.ByteString getEncryptedChallenge();
  }
  /**
   * Protobuf type {@code com.datmedia.mediaplayer.androidrequestresponse.EnrollmentConfirmation}
   */
  public static final class EnrollmentConfirmation extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.datmedia.mediaplayer.androidrequestresponse.EnrollmentConfirmation)
      EnrollmentConfirmationOrBuilder {
    // Use EnrollmentConfirmation.newBuilder() to construct.
    private EnrollmentConfirmation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EnrollmentConfirmation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EnrollmentConfirmation defaultInstance;
    public static EnrollmentConfirmation getDefaultInstance() {
      return defaultInstance;
    }

    public EnrollmentConfirmation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EnrollmentConfirmation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              deviceId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              encryptedChallenge_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EnrollmentConfirmationOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_EnrollmentConfirmation_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EnrollmentConfirmationOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_EnrollmentConfirmation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EnrollmentConfirmation.class, Builder.class);
    }

    public static com.google.protobuf.Parser<EnrollmentConfirmation> PARSER =
        new com.google.protobuf.AbstractParser<EnrollmentConfirmation>() {
      public EnrollmentConfirmation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnrollmentConfirmation(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<EnrollmentConfirmation> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DEVICEID_FIELD_NUMBER = 1;
    private int deviceId_;
    /**
     * <code>required int32 DeviceId = 1;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 DeviceId = 1;</code>
     */
    public int getDeviceId() {
      return deviceId_;
    }

    public static final int ENCRYPTEDCHALLENGE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString encryptedChallenge_;
    /**
     * <code>required bytes EncryptedChallenge = 2;</code>
     */
    public boolean hasEncryptedChallenge() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes EncryptedChallenge = 2;</code>
     */
    public com.google.protobuf.ByteString getEncryptedChallenge() {
      return encryptedChallenge_;
    }

    private void initFields() {
      deviceId_ = 0;
      encryptedChallenge_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEncryptedChallenge()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, deviceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, encryptedChallenge_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, deviceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, encryptedChallenge_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static EnrollmentConfirmation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnrollmentConfirmation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnrollmentConfirmation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnrollmentConfirmation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnrollmentConfirmation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EnrollmentConfirmation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static EnrollmentConfirmation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static EnrollmentConfirmation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static EnrollmentConfirmation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EnrollmentConfirmation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(EnrollmentConfirmation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.datmedia.mediaplayer.androidrequestresponse.EnrollmentConfirmation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.datmedia.mediaplayer.androidrequestresponse.EnrollmentConfirmation)
        EnrollmentConfirmationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EnrollmentConfirmationOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_EnrollmentConfirmation_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EnrollmentConfirmationOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_EnrollmentConfirmation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EnrollmentConfirmation.class, Builder.class);
      }

      // Construct using com.datmedia.mediaplayer.androidrequestresponse.EnrollmentConfirmationOuterClass.EnrollmentConfirmation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deviceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        encryptedChallenge_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EnrollmentConfirmationOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_EnrollmentConfirmation_descriptor;
      }

      public EnrollmentConfirmation getDefaultInstanceForType() {
        return EnrollmentConfirmation.getDefaultInstance();
      }

      public EnrollmentConfirmation build() {
        EnrollmentConfirmation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public EnrollmentConfirmation buildPartial() {
        EnrollmentConfirmation result = new EnrollmentConfirmation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.encryptedChallenge_ = encryptedChallenge_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EnrollmentConfirmation) {
          return mergeFrom((EnrollmentConfirmation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EnrollmentConfirmation other) {
        if (other == EnrollmentConfirmation.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          setDeviceId(other.getDeviceId());
        }
        if (other.hasEncryptedChallenge()) {
          setEncryptedChallenge(other.getEncryptedChallenge());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDeviceId()) {
          
          return false;
        }
        if (!hasEncryptedChallenge()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EnrollmentConfirmation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EnrollmentConfirmation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int deviceId_ ;
      /**
       * <code>required int32 DeviceId = 1;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 DeviceId = 1;</code>
       */
      public int getDeviceId() {
        return deviceId_;
      }
      /**
       * <code>required int32 DeviceId = 1;</code>
       */
      public Builder setDeviceId(int value) {
        bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 DeviceId = 1;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString encryptedChallenge_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes EncryptedChallenge = 2;</code>
       */
      public boolean hasEncryptedChallenge() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes EncryptedChallenge = 2;</code>
       */
      public com.google.protobuf.ByteString getEncryptedChallenge() {
        return encryptedChallenge_;
      }
      /**
       * <code>required bytes EncryptedChallenge = 2;</code>
       */
      public Builder setEncryptedChallenge(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        encryptedChallenge_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes EncryptedChallenge = 2;</code>
       */
      public Builder clearEncryptedChallenge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        encryptedChallenge_ = getDefaultInstance().getEncryptedChallenge();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.datmedia.mediaplayer.androidrequestresponse.EnrollmentConfirmation)
    }

    static {
      defaultInstance = new EnrollmentConfirmation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.datmedia.mediaplayer.androidrequestresponse.EnrollmentConfirmation)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datmedia_mediaplayer_androidrequestresponse_EnrollmentConfirmation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_datmedia_mediaplayer_androidrequestresponse_EnrollmentConfirmation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034EnrollmentConfirmation.proto\022/com.datm" +
      "edia.mediaplayer.androidrequestresponse\"" +
      "F\n\026EnrollmentConfirmation\022\020\n\010DeviceId\030\001 " +
      "\002(\005\022\032\n\022EncryptedChallenge\030\002 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_datmedia_mediaplayer_androidrequestresponse_EnrollmentConfirmation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_datmedia_mediaplayer_androidrequestresponse_EnrollmentConfirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_datmedia_mediaplayer_androidrequestresponse_EnrollmentConfirmation_descriptor,
        new String[] { "DeviceId", "EncryptedChallenge", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
