// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InitialRequest.proto

package com.datmedia.mediaplayer.messages.Enrollment;

public final class InitialRequestOuterClass {
  private InitialRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.datmedia.mediaplayer.androidrequestresponse.DevicePlatform}
   */
  public enum DevicePlatform
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Windows = 0;</code>
     */
    Windows(0, 0),
    /**
     * <code>Android = 1;</code>
     */
    Android(1, 1),
    /**
     * <code>Chrome = 2;</code>
     */
    Chrome(2, 2),
    ;

    /**
     * <code>Windows = 0;</code>
     */
    public static final int Windows_VALUE = 0;
    /**
     * <code>Android = 1;</code>
     */
    public static final int Android_VALUE = 1;
    /**
     * <code>Chrome = 2;</code>
     */
    public static final int Chrome_VALUE = 2;


    public final int getNumber() { return value; }

    public static DevicePlatform valueOf(int value) {
      switch (value) {
        case 0: return Windows;
        case 1: return Android;
        case 2: return Chrome;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DevicePlatform>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DevicePlatform>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DevicePlatform>() {
            public DevicePlatform findValueByNumber(int number) {
              return DevicePlatform.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return InitialRequestOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final DevicePlatform[] VALUES = values();

    public static DevicePlatform valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private DevicePlatform(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.datmedia.mediaplayer.androidrequestresponse.DevicePlatform)
  }

  public interface InitialRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.datmedia.mediaplayer.androidrequestresponse.InitialRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes DevicePublicKey = 1;</code>
     */
    boolean hasDevicePublicKey();
    /**
     * <code>required bytes DevicePublicKey = 1;</code>
     */
    com.google.protobuf.ByteString getDevicePublicKey();

    /**
     * <code>required .com.datmedia.mediaplayer.androidrequestresponse.DevicePlatform DevicePlatform = 2;</code>
     */
    boolean hasDevicePlatform();
    /**
     * <code>required .com.datmedia.mediaplayer.androidrequestresponse.DevicePlatform DevicePlatform = 2;</code>
     */
    DevicePlatform getDevicePlatform();
  }
  /**
   * Protobuf type {@code com.datmedia.mediaplayer.androidrequestresponse.InitialRequest}
   */
  public static final class InitialRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.datmedia.mediaplayer.androidrequestresponse.InitialRequest)
      InitialRequestOrBuilder {
    // Use InitialRequest.newBuilder() to construct.
    private InitialRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InitialRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InitialRequest defaultInstance;
    public static InitialRequest getDefaultInstance() {
      return defaultInstance;
    }

    public InitialRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InitialRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              devicePublicKey_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              DevicePlatform value = DevicePlatform.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                devicePlatform_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return InitialRequestOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_InitialRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return InitialRequestOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_InitialRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InitialRequest.class, Builder.class);
    }

    public static com.google.protobuf.Parser<InitialRequest> PARSER =
        new com.google.protobuf.AbstractParser<InitialRequest>() {
      public InitialRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InitialRequest(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<InitialRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DEVICEPUBLICKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString devicePublicKey_;
    /**
     * <code>required bytes DevicePublicKey = 1;</code>
     */
    public boolean hasDevicePublicKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes DevicePublicKey = 1;</code>
     */
    public com.google.protobuf.ByteString getDevicePublicKey() {
      return devicePublicKey_;
    }

    public static final int DEVICEPLATFORM_FIELD_NUMBER = 2;
    private DevicePlatform devicePlatform_;
    /**
     * <code>required .com.datmedia.mediaplayer.androidrequestresponse.DevicePlatform DevicePlatform = 2;</code>
     */
    public boolean hasDevicePlatform() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.datmedia.mediaplayer.androidrequestresponse.DevicePlatform DevicePlatform = 2;</code>
     */
    public DevicePlatform getDevicePlatform() {
      return devicePlatform_;
    }

    private void initFields() {
      devicePublicKey_ = com.google.protobuf.ByteString.EMPTY;
      devicePlatform_ = DevicePlatform.Windows;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDevicePublicKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDevicePlatform()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, devicePublicKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, devicePlatform_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, devicePublicKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, devicePlatform_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static InitialRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InitialRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InitialRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InitialRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InitialRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static InitialRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static InitialRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static InitialRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static InitialRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static InitialRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(InitialRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.datmedia.mediaplayer.androidrequestresponse.InitialRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.datmedia.mediaplayer.androidrequestresponse.InitialRequest)
        InitialRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return InitialRequestOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_InitialRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return InitialRequestOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_InitialRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                InitialRequest.class, Builder.class);
      }

      // Construct using com.datmedia.mediaplayer.androidrequestresponse.InitialRequestOuterClass.InitialRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        devicePublicKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        devicePlatform_ = DevicePlatform.Windows;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return InitialRequestOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_InitialRequest_descriptor;
      }

      public InitialRequest getDefaultInstanceForType() {
        return InitialRequest.getDefaultInstance();
      }

      public InitialRequest build() {
        InitialRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public InitialRequest buildPartial() {
        InitialRequest result = new InitialRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.devicePublicKey_ = devicePublicKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.devicePlatform_ = devicePlatform_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof InitialRequest) {
          return mergeFrom((InitialRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(InitialRequest other) {
        if (other == InitialRequest.getDefaultInstance()) return this;
        if (other.hasDevicePublicKey()) {
          setDevicePublicKey(other.getDevicePublicKey());
        }
        if (other.hasDevicePlatform()) {
          setDevicePlatform(other.getDevicePlatform());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDevicePublicKey()) {
          
          return false;
        }
        if (!hasDevicePlatform()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        InitialRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (InitialRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString devicePublicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes DevicePublicKey = 1;</code>
       */
      public boolean hasDevicePublicKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes DevicePublicKey = 1;</code>
       */
      public com.google.protobuf.ByteString getDevicePublicKey() {
        return devicePublicKey_;
      }
      /**
       * <code>required bytes DevicePublicKey = 1;</code>
       */
      public Builder setDevicePublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        devicePublicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes DevicePublicKey = 1;</code>
       */
      public Builder clearDevicePublicKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        devicePublicKey_ = getDefaultInstance().getDevicePublicKey();
        onChanged();
        return this;
      }

      private DevicePlatform devicePlatform_ = DevicePlatform.Windows;
      /**
       * <code>required .com.datmedia.mediaplayer.androidrequestresponse.DevicePlatform DevicePlatform = 2;</code>
       */
      public boolean hasDevicePlatform() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.datmedia.mediaplayer.androidrequestresponse.DevicePlatform DevicePlatform = 2;</code>
       */
      public DevicePlatform getDevicePlatform() {
        return devicePlatform_;
      }
      /**
       * <code>required .com.datmedia.mediaplayer.androidrequestresponse.DevicePlatform DevicePlatform = 2;</code>
       */
      public Builder setDevicePlatform(DevicePlatform value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        devicePlatform_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.datmedia.mediaplayer.androidrequestresponse.DevicePlatform DevicePlatform = 2;</code>
       */
      public Builder clearDevicePlatform() {
        bitField0_ = (bitField0_ & ~0x00000002);
        devicePlatform_ = DevicePlatform.Windows;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.datmedia.mediaplayer.androidrequestresponse.InitialRequest)
    }

    static {
      defaultInstance = new InitialRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.datmedia.mediaplayer.androidrequestresponse.InitialRequest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datmedia_mediaplayer_androidrequestresponse_InitialRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_datmedia_mediaplayer_androidrequestresponse_InitialRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024InitialRequest.proto\022/com.datmedia.med" +
      "iaplayer.androidrequestresponse\"\202\001\n\016Init" +
      "ialRequest\022\027\n\017DevicePublicKey\030\001 \002(\014\022W\n\016D" +
      "evicePlatform\030\002 \002(\0162?.com.datmedia.media" +
      "player.androidrequestresponse.DevicePlat" +
      "form*6\n\016DevicePlatform\022\013\n\007Windows\020\000\022\013\n\007A" +
      "ndroid\020\001\022\n\n\006Chrome\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_datmedia_mediaplayer_androidrequestresponse_InitialRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_datmedia_mediaplayer_androidrequestresponse_InitialRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_datmedia_mediaplayer_androidrequestresponse_InitialRequest_descriptor,
        new String[] { "DevicePublicKey", "DevicePlatform", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
