// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseContents.proto

package com.datmedia.mediaplayer.messages.Enrollment;

public final class ResponseContentsOuterClass {
  private ResponseContentsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.datmedia.mediaplayer.androidrequestresponse.ResponseType}
   */
  public enum ResponseType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>InitialResponse = 0;</code>
     */
    InitialResponse(0, 0),
    /**
     * <code>Confirmation = 1;</code>
     */
    Confirmation(1, 1),
    ;

    /**
     * <code>InitialResponse = 0;</code>
     */
    public static final int InitialResponse_VALUE = 0;
    /**
     * <code>Confirmation = 1;</code>
     */
    public static final int Confirmation_VALUE = 1;


    public final int getNumber() { return value; }

    public static ResponseType valueOf(int value) {
      switch (value) {
        case 0: return InitialResponse;
        case 1: return Confirmation;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
            public ResponseType findValueByNumber(int number) {
              return ResponseType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ResponseContentsOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResponseType[] VALUES = values();

    public static ResponseType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ResponseType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.datmedia.mediaplayer.androidrequestresponse.ResponseType)
  }

  public interface ResponseContentsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.datmedia.mediaplayer.androidrequestresponse.ResponseContents)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.datmedia.mediaplayer.androidrequestresponse.ResponseType ResponseType = 1;</code>
     */
    boolean hasResponseType();
    /**
     * <code>required .com.datmedia.mediaplayer.androidrequestresponse.ResponseType ResponseType = 1;</code>
     */
    ResponseType getResponseType();

    /**
     * <code>required bytes Data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>required bytes Data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.datmedia.mediaplayer.androidrequestresponse.ResponseContents}
   */
  public static final class ResponseContents extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.datmedia.mediaplayer.androidrequestresponse.ResponseContents)
      ResponseContentsOrBuilder {
    // Use ResponseContents.newBuilder() to construct.
    private ResponseContents(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResponseContents(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResponseContents defaultInstance;
    public static ResponseContents getDefaultInstance() {
      return defaultInstance;
    }

    public ResponseContents getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseContents(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ResponseType value = ResponseType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                responseType_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ResponseContentsOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_ResponseContents_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ResponseContentsOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_ResponseContents_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResponseContents.class, Builder.class);
    }

    public static com.google.protobuf.Parser<ResponseContents> PARSER =
        new com.google.protobuf.AbstractParser<ResponseContents>() {
      public ResponseContents parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseContents(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<ResponseContents> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESPONSETYPE_FIELD_NUMBER = 1;
    private ResponseType responseType_;
    /**
     * <code>required .com.datmedia.mediaplayer.androidrequestresponse.ResponseType ResponseType = 1;</code>
     */
    public boolean hasResponseType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.datmedia.mediaplayer.androidrequestresponse.ResponseType ResponseType = 1;</code>
     */
    public ResponseType getResponseType() {
      return responseType_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes Data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes Data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      responseType_ = ResponseType.InitialResponse;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResponseType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, responseType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, responseType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ResponseContents parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseContents parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseContents parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseContents parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseContents parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ResponseContents parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ResponseContents parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ResponseContents parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ResponseContents parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ResponseContents parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ResponseContents prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.datmedia.mediaplayer.androidrequestresponse.ResponseContents}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.datmedia.mediaplayer.androidrequestresponse.ResponseContents)
        ResponseContentsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ResponseContentsOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_ResponseContents_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ResponseContentsOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_ResponseContents_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResponseContents.class, Builder.class);
      }

      // Construct using com.datmedia.mediaplayer.androidrequestresponse.ResponseContentsOuterClass.ResponseContents.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        responseType_ = ResponseType.InitialResponse;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ResponseContentsOuterClass.internal_static_com_datmedia_mediaplayer_androidrequestresponse_ResponseContents_descriptor;
      }

      public ResponseContents getDefaultInstanceForType() {
        return ResponseContents.getDefaultInstance();
      }

      public ResponseContents build() {
        ResponseContents result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ResponseContents buildPartial() {
        ResponseContents result = new ResponseContents(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.responseType_ = responseType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResponseContents) {
          return mergeFrom((ResponseContents)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResponseContents other) {
        if (other == ResponseContents.getDefaultInstance()) return this;
        if (other.hasResponseType()) {
          setResponseType(other.getResponseType());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResponseType()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ResponseContents parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ResponseContents) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private ResponseType responseType_ = ResponseType.InitialResponse;
      /**
       * <code>required .com.datmedia.mediaplayer.androidrequestresponse.ResponseType ResponseType = 1;</code>
       */
      public boolean hasResponseType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.datmedia.mediaplayer.androidrequestresponse.ResponseType ResponseType = 1;</code>
       */
      public ResponseType getResponseType() {
        return responseType_;
      }
      /**
       * <code>required .com.datmedia.mediaplayer.androidrequestresponse.ResponseType ResponseType = 1;</code>
       */
      public Builder setResponseType(ResponseType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        responseType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.datmedia.mediaplayer.androidrequestresponse.ResponseType ResponseType = 1;</code>
       */
      public Builder clearResponseType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        responseType_ = ResponseType.InitialResponse;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes Data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes Data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes Data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes Data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.datmedia.mediaplayer.androidrequestresponse.ResponseContents)
    }

    static {
      defaultInstance = new ResponseContents(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.datmedia.mediaplayer.androidrequestresponse.ResponseContents)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datmedia_mediaplayer_androidrequestresponse_ResponseContents_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_datmedia_mediaplayer_androidrequestresponse_ResponseContents_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026ResponseContents.proto\022/com.datmedia.m" +
      "ediaplayer.androidrequestresponse\"u\n\020Res" +
      "ponseContents\022S\n\014ResponseType\030\001 \002(\0162=.co" +
      "m.datmedia.mediaplayer.androidrequestres" +
      "ponse.ResponseType\022\014\n\004Data\030\002 \002(\014*5\n\014Resp" +
      "onseType\022\023\n\017InitialResponse\020\000\022\020\n\014Confirm" +
      "ation\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_datmedia_mediaplayer_androidrequestresponse_ResponseContents_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_datmedia_mediaplayer_androidrequestresponse_ResponseContents_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_datmedia_mediaplayer_androidrequestresponse_ResponseContents_descriptor,
        new String[] { "ResponseType", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
